version: '3.4'

services:
  dockerinstall:
    image: dockerinstall
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m ConsciousAI "]
    ports:
      - 5678:5678
