name: docker-install CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os:
          - ubuntu:22.04
          - ubuntu:24.04
          - quay.io/centos/centos:stream9
        version:
          - "27.5"
          - ""

    steps:
    - uses: actions/checkout@v3
    - name: Shellcheck
      env:
        GH_TOKEN: ${{ github.token }}
      run: make shellcheck
    - name: Check distribution
      env:
        GH_TOKEN: ${{ github.token }}
      run: TEST_IMAGE=${{ matrix.os }} VERSION=${{ matrix.version }} make test

  # This is a separate workflow step, because we need to check it outside of container (due to lsmod, iptables checks)
  test-install-rootless:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Install rootless
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        sudo sh -c 'echo 0 > /proc/sys/kernel/apparmor_restrict_unprivileged_userns'
        make build/test/rootless-install.sh
        FORCE_ROOTLESS_INSTALL=1 ./build/test/rootless-install.sh
    
