name: Diff

on:
  pull_request:

jobs:
  diff:
    name: Diff
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Diff stable
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            make CHANNEL=stable diff

      - name: Diff test
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            make CHANNEL=test diff

